### ISSUE TITLE
Theme is reset after 3 deaths

### ISSUE THREAD

**Issue by blairezy** [kchynes/SuperWorm#18] opened 2015-03-05 01:42 UTC
1. Select a theme from the start menu 
2. Die 3 times without changing anything in the menu 
3. The theme is reset to the default basic theme.

**Comment by johndrevniok** [comment] 2015-05-21 21:59
I tested it again and yes the issue is fixed.
The theme does not reset after three deaths.
The issue should be closed unless I am missing something?

**Comment by kchynes** [comment] 2015-05-22 02:16
Yup I forgot to close it. I don't know if you guys can do that, but Ill do it now. Merci!

**Closed as completed by kchynes** 2015-05-22 02:16 UTC
